version: "3.9"
services:
  fairgame:
    image: kaliburg/fairgame:staging
    environment:
      SPRING_PROFILE: ${PROFILE}
      POSTGRES_URL: jdbc:postgresql://postgres:5432/FairGameStaging
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MONGO_URL: mongodb://root:${MONGO_PASSWORD}@mongo:27017/FairGameStaging?authMechanism=DEFAULT
      MONGO_HOST: mongo
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      REMEMBER_ME_SECRET: ${REMEMBER_ME_SECRET}
      SPARK_MASTER_URL: https://spark.kaliburg.de
    ports:
      - "10100:8080"
    depends_on:
      - postgres
      - redis
      - mongo
    restart: unless-stopped
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: FairGameStaging
    ports:
      - "10101:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "10102:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    restart: always
  redis:
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass $REDIS_PASSWORD"
    environment:
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "10103:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  mongo_data:
  mongo_config:
  redis_data: